### ISSUE TITLE
USER STORY: Create Heroku App

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#1]
### User Story:
As a **developer**, I can **create an account with Heroku to process setting up the app** so that **I can deploy my site to Heroku**
#
### Tasks:

- [x] Create a Heroku account at https://heroku.com
- [x] Make the primary development language 'Python'
- [x] Validate confirmation email
- [x] Set password
#
- [x] Create a new App from your dashboard and choose the relevant region

#
