### ISSUE TITLE
USER STORY: View a Recipe 

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#11]
### User Story:
As a **user**, I can **view recipes**, without **having to sign-up to enjoy the site's content**
#

### Acceptance Criteria:
- In the nav section there should be a heading for **'Recipes'** which any user can click on to **view recipes**
   - When a user is logged-in, This heading should change to **'My recipes'**
- Recipes should be styled as cards displaying the **title**, **prep time** & **cook time**
   - When the card is clicked, it opens up the recipe on a separate page with all of the recipe content

#
### Tasks:
- [x] Create a 'Recipes' tab in the navigation section of the homepage
- [x] Create a heading in the nav section for when a user is logged in that turns 'Recipes' into 'My recipes'
    - `{% if user.is_authenticated %}`
- [x] Create recipes landing page
- [x] Create basic cards to display recipe title, photo, cook time, and quantity made
     -  use bootstrap to make responsive
