### ISSUE TITLE
USER STORY: Responsive on a mobile device

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#13]
### User Story:
As a **User**, I can **view recipes on my mobile** so that **I don't have to rely on using a computer**
#

### Acceptance Criteria:
- As a user, I should be able to view recipes on a wide range of devices including tablets, laptops & iOS devices 
- Most used devices should be taken into consideration
- Font must be legible and any navigation links are easy to click on a small device
#

### Tasks:
- [x] Develop a responsive layout for the recipe cards using **bootstrap**
- [x] Reduce picture content and focus on ingredients and method displayed for small devices
   - A drop-down bar that the user can click to open and close content such as ingredients
- [x] **Test Responsive design** 
    - Am I responsive - https://ui.dev/amiresponsive
    - Chrome DevTools
    - Lighthouse
