### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#14]
### User Story:
As a **User**, I can **navigate around the site** so that **I can easily view desired content**
#

### Acceptance Criteria: 
- The nav bar section should be fixed to the top of the screen which will allow users to navigate to their desired content
- A heading in the nav section or social icons should be interactive - have a hover effect on them so the user knows that they are interacting with site content
- All images/links have alt tags for **accessibility**

##

### Related User Stories:

#

### Tasks:
- [x] Create a nav section at the top of the base.html view using bootstrap
- [x] Make headings/ icons interactive when hovered over
   - CSS `:hover`
- [x] Fix navbar into position
     - Collapse the navbar section into a drop-down hamburger icon for mobile devices

#
