### ISSUE TITLE
USER STORY: Search for a recipe

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#15]
### User Story:
As a **User**, I can **search for the desirable recipe by keyword** so that **I can find a specific recipe fast**
#

### Ideas:
- A search input within the navbar or in a separate section within the homepage
- Show hints or related dishes if no search results come up 
#
### Acceptance Criteria:
- When a user searches the site using a keyword, a new 'searched results' page should load with the results
- A user should be able to type a keyword such as cheese and any dish which has 'cheese' within the ingredients is shown in the results
- The search bar should only accept a certain amount of characters
- The search bar should be available for all users to search, not just authenticated users
#

### Related User Stories:
#11 - View a recipe - As a **User**, I can **view recipes**, **without having to sign-up to enjoy the site's content**
#

### Tasks:
- [x] Create a search option input field in the nav section of the base template
- [x] Create a search view with a request post to render the results 
- [x] Create a searched results template with same style rules to all_recipes
    - Ensure searched results is paginated
~~- [ ] Add a 'you might also like' section under searched results for recipes related to searched keywords~~

#
