### ISSUE TITLE
USER STORY: Delete a recipe

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#19]
### User Story:
As a **logged-in User** I can **delete any personal recipes** so that **I can remove them if necessary**
#

### Acceptance Criteria:
- Only a **logged-in User** can **delete** a recipe
- If a **User** is **logged in**, a **delete** button should be shown on the user-created recipes page
- The **User** should confirm if they want to **delete** the recipe or not with a cancel option
- If the **User** confirms **deletion**, the recipe should be removed from the database
- The **logged-in User** should be notified that they have **successfully deleted** the recipe
#
### Related User Stories:
#
### Tasks:
- [x] Create a class in views.py
- [x] Create a 'Delete' button that appears next to the recipe only on user's created recipes page
    - [x] Ensure the User is logged-in before a delete button appears and only display if the user is the author of the recipe
- [x] Create a delete recipe view
- [x] Wire up URL to render template
- [x] Create an alert message to the user for the successful deletion of their recipe

#
