### ISSUE TITLE
USER STORY: Create Config Vars & static files

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#2]
### User Story:
As a **developer**, I can **add my config vars to my app in Heroku** so that **I can allow deployment to production**
#
### Related User Stories:
#1 **Create Heroku App**

#4 **Cloudinary Setup**
#
### Tasks:
- [x] Login to your Heroku account and select the App
- [x] Go to the settings tab and scroll down to Config Vars
- [x] #4 Setup Cloudinary
- [x] Add correct config vars
  - [x] `CLOUDINARY_URL`
  - [x] `DATABASE_URL`
  - [x] `SECRET_KEY`
  - [x] `PORT` - `8000`
  - [x] `DISABLE_COLLECTSTATIC` - `1`  (only used for development)

- [x] Copy Cloudinary API Environment variable in your Cloudinary dashboard
- [x] Add variable to your `env.py` file
- [x] Add `'cloudinary_storage'` & `'cloudinary'` to `INSTALLED_APPS`
- [x] Tell Django to use Cloudinary to store our static files
- [x] Add to `settings.py` - 
                 `STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'`
                 `STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]`
                 `STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')`
                 `MEDIA_URL = '/media/'`
                 `DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'`

- [x] Add to the build paths - 
  - `TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')`
- [x] Add 'DIRS': `[TEMPLATES_DIR],` to `TEMPLATES`

- [x] Add Heroku host name to `ALLOWED_HOSTS`
    - `ALLOWED_HOSTS = ['kitchen-tales.herokuapp.com', 'localhost']` (localhost is added so we can run it locally)

- [x] Create 3 new folders in the top level of the project
  - 'media'
  - 'static'
  - 'templates'
 

#
