### ISSUE TITLE
USER STORY: Register for an account

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#22]
### User Story:
As a **User**, I can **register for an account** so that **I can interact with the site content**
#
### Ideas:
- Add a captcha for security
- Use more than one method to sign up 
     - phone number
     - social accounts such as Facebook, Instagram, and Twitter
- When a user tries to interact with site content without logging in or signing up, prompt for either.
#

### Acceptance Criteria:
- A signup button should be visible on the homepage
- When a user clicks on the sign-up button, it should take them to the sign-up page/form
- The form must be inputted correctly for the account to be made 
- The user should be alerted of a successful account creation 
- When a user has created an account, they should be taken to their homepage 

#
### Related User Stories:

#

### Tasks:
- [x] Create a register page/ edit the login template page
- [ ] Prompt the user to sign-up or log in if they try to interact with site content without logging in first. Create pop up modal of the login page/sign-up link
- [x] Use Django's built-in authentication method to create accounts 
- [x] Link the Registration page to the navbar

#
