### ISSUE TITLE
USER STORY: Register for an account using my social media

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#23]
### User Story:

As a **User,** I can **register for an account by using one of my social media accounts** so that **I can use an alternative method of signing up**
#
### Ideas:
- Use the **most popular** social media platforms for alternative login methods:
     - Facebook
     - Twitter
     - Instagram

#

### Acceptance Criteria: 
- After clicking 'sign up with an alternative method', the user should be redirected to a new window for sign-in via social media
- After signing in with social media, the user should be redirected back to the homepage of Kitchen Tales

#
### Related User Stories:
#22 -  **Register for an account**
#

### Tasks:
- [ ] Install Django Social Auth App
   - [ ] `pip install social-auth-app-django`
   - [ ] Add `social_django` to `INSTALLED_APPS:`
- [ ] Migrate database
- [ ] Update URLs
- [ ] Update Views
- [ ] Create App from social accounts 
     - developers.facebook.com
     - apps.twitter.com

#
