### ISSUE TITLE
USER STORY: Login to my account

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#24]
### User Story:
As a **User**, I can **log into my account** so that **I can manage my recipes**
#
### Acceptance Criteria:
- The user should have a button displayed in the navbar to sign into their account 
- The sign-in button should take the user to a sign-in page
- If user credentials are correct, the user will be signed in
- If user credentials are incorrect, the user will be prompted with an error alert

#
### Related User Stories:
#22 **Register for an account**

#23 **Register for an account using my social media**

#

### Tasks:
- [x] Create a sign-in Page
    - Preferably a modal-style pop-up for easy sign in
- [x] Use Django's built-in authentication method to create a login for a user
- [x] Add a template
- [x] Add URL paths
- [x] Create link to the sign-in page from the navbar

#

**Comment by chris-townsend** [comment]
closed with commit https://github.com/chris-townsend/PP4-Kitchen_Tales/commit/f6ac274f4f9582a09a148b7f42600c22f6fc30a9
