### ISSUE TITLE
USER STORY: Logout of my account

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#25]
### User Story:

As a **User**, I can **safely log out of my account** so that **I can disconnect from the site**
#

### Ideas:
- A confirmation alert to the user after clicking the sign-out button to confirm or cancel sign-out
#

### Acceptance Criteria:
- A user must be logged in to be given the option to sign out
- When the user has successfully logged out, they should be brought back to the sign-in page or homepage
- Member features should not be shown after logging out

#

### Related User Stories:

#24 -  **Login to my account**
#

### Tasks:
- [x] Install django allauth and add to `INSTALLED_APPS`
- [x] Add allauth URLS 
- [x] Add links to sign-out page from homepage
- [x] Create a sign-out template
~~Preferably a modal style pop-up alerting the user they have signed out of their account~~
- [ ] Alert the user for a successful logout of their account
