### ISSUE TITLE
USER STORY: Login status

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#26]
### User Story:
As a **logged-in User**, I can **see my login status** so that **I know if I am logged in or out of my account**
#
### Ideas:
- A change in the navbar or a symbol showing the login status
#
### Acceptance Criteria:
- A user should know if they're logged in or not by looking at the navbar either displaying Login/Signup or Logout
- An notification should alert the user when logging in or out to confirm login or out
#

### Related User Stories:

#24 - **Login to my account**

#25 - **Logout of my account**
#

### Tasks:
- [x] Use Django's built-in authentication system to build a user base system
- [x] In the nav section of the homepage create an if statement which checks if a user is authenticated or not
     - `{% if user.is_authenticated %}` - add logged-in status tabs
- [x]  Change the template so that it displays a users login status

#
