### ISSUE TITLE
USER STORY: Change my password

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#27]
### User Story:
As a **logged-in User**, I can **change my password** so that **I can keep my account secure**
#

### Acceptance Criteria:
- A user can only change their password if they are authenticated
- A user should be taken to a new page to change their password
- A user should receive a notification of a successful password change
- A user should be prompted to sign in again after a password change
#
### Related User Stories:
#27 - **Request a password reminder**
#

### Tasks:
- [ ] Use Django's built-in authentication method to create a change password function for a user
- [ ] Create a change password modal/view 
- [ ] Create a notification to let the user know that their password has been changed successfully

#
