### ISSUE TITLE
USER STORY: Admin CRUD features

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#28]
### User Story:
As a **Site admin**, I can **create, edit and delete recipes and comments** so that **I can control the site content**
#
### Acceptance Criteria:
- Only a site admin can delete/ edit another user's recipe
- The recipe must be put under review until it has been reviewed by a site admin

#
### Related User Stories:
#6 - **Django Setup**
#
### Tasks:
- [x] Set up a superuser in Django to gain admin functionality
- [x] run `python3 manage.py createsuperuser`
     - Enter username & password of choice
- [x] Now login into the Django Admin page by running the command `python3 manage.py runserver`
     - Open a Web browser and go to “/admin/”

#
