### ISSUE TITLE
USER STORY: Authorize recipes and comments

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#29]
### User Story:
As a **Site admin**, I can **authorize recipes and comments** so that **I can review the content before it's made public**
#

### Accepted Criteria:
- The user must be authenticated to make a request to post a recipe or comment
- The user should be alerted if they successfully make a request to post 
- The user should be alerted if their recipe or comment successfully joins the site

#

### Related User Stories:
#28 -  **Admin CRUD features**
#6 - **Django Setup**
#

### Tasks:
- [ ] Use Django's built-in administration settings
- [ ] Actions Method:
    - Add `actions = ['approve_comments']` to `admin.py`  ( any function names)
- [ ] Add `approve_comments` method
- [ ] Use `queryset` to update the records 

#
