### ISSUE TITLE
USER STORY: Create Procfile

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#3]
### User Story:
As a **developer**, I can **create a Procfile within my project** so that **the application will run in Heroku**
#
### Procfile Format:
A Procfile declares its process types on individual lines, each with the following format:

`<process type>: <command>`

`<process type>` is an alphanumeric name for your command, such as `web`, `worker`, `urgentworker`, `clock`, and so on.

`<command>` indicates the command that every dyno of the process type should execute on startup, such as `rake jobs:work`.
#

### Related User Stories:
#

### Tasks:
- [x] Install necessary dependencies for the project to run
- [x] Add Procfile to the root directory of your project
- [x] Ensure Heroku knows what language we're using -  'Python'
   - [x] Commit and Push Changes

#
