### ISSUE TITLE
USER STORY: Add a captcha for sign-up

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#30]
### User Story:
As a **Site Admin**, I would like to **ensure that the majority of my site users are real** so that **I can prevent any spam content**
#
### Ideas:
**Django simple captcha** - https://django-simple-captcha.readthedocs.io/en/latest/usage.html
#
### Acceptance Criteria:
- The user should have to input the captcha before they can log in to their account
- The captcha must be displayed before the option to sign-in/ sign up

#
### Related User Stories:

#22 - **Register for an account**
#23 - **Register for an account using my social media**
#

### Tasks:
- [ ] Install `django-simple-captcha` using `pip3 install django-simple-captcha`
- [ ] Add the captcha to the `INSTALLED_APPS` in `settings.py`
- [ ] Run `python3 manage.py migrate`
- [ ] Add the entry to `urls.py`

#
