### ISSUE TITLE
USER STORY: Populate a recipe database using an API

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#32]
### User Story:
As a **Site owner**, I can **provide a database of existing recipes** so that **I can provide my users with content**
#
### Ideas:
-  **Best recipe APIs for developers 2022** -  https://rapidapi.com/blog/recipe-apis/
- **A collective list of free APIs** - https://github.com/public-apis/public-apis
#

### Acceptance Criteria:
- The user should know the difference between a user-created recipe and a recipe found in an API 
    - displayed as 'submitted by' or 'recipe by' under the recipe
- The search bar feature should work in sync with the API to pick up any keywords within the database that a user searches for
#

### Tasks:
- [ ] Find a suitable API that will reflect the desired information (recipe related)
- [ ] Retrieve API key
- [ ] Set access permissions
- [ ] Ensure relevant keys are kept private
- [ ] Create requests to pull data
- [ ] Connect to App 

#
