### ISSUE TITLE
USER STORY: Comment on a recipe

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#35]
### User Story:
As a **Logged-in User**, I can **comment on recipes** so that **I can leave my feedback for others**
#

### Acceptance Criteria:
- Only a logged-in user can submit a comment 
- The comment box should only appear if your signed-in 

#
### Related User Stories:
#34 - **View comments**
#36 - **Comment Approval**
#
### Tasks:
- [x] Create a form for the comments to be written and displayed
- [x] Create a comment section underneath the recipe section in `all_recipes.html`
- [x] Add a submit button underneath the input text field
- [x] Add the necessary code to handle the form data and update the database `views.py`
- [x]  Create an alert to the user such as a 'Thanks, your comment is under review'
#
