### ISSUE TITLE
USER STORY: Contact the site owner

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#37]
### User Story:
As a **User**, I can **contact the site owner** so that **I can offer my feedback**
#
### Ideas:
- Create a contact page with a form to submit to the site owner
- Create a contact page for only when a user is authenticated
- Display an email icon next to the social media icons which will automatically open the user's email template with the owner's email address auto-filled
#

### Acceptance Criteria:
- When the form is submitted the user should be notified as an alert that their email has been sent
- The form should only accept the correct data e.g. email input only accepts email addresses
#

### Related User Stories:
#31 - **Display my social icons**
#

### Tasks:
- [ ] Create a contact page 
- [ ] Create a basic contact form (fields - name/email/message)
- [ ] Create a link to the contact page in the nav bar
