### ISSUE TITLE
USER STORY: View my liked recipes

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#39]
### User Story:
As a **Logged-in user** I can **view my liked recipes** so that **I can return to them easily**
#
### Acceptance Criteria:
- A user has to create an account to receive their own favorites list 
- A user must be logged in to see a 'favorites' or 'My liked Recipes' tab
- A recipe should be added to a user's favorite list after a user clicks the like button on a recipe
   - if authenticated
#
### Related User Stories:
#12 - **View most liked recipes**
#

### Tasks:
- [x] Create a 'favorites' or 'My liked Recipes' tab in the navigation bar for when a user is logged in
- [x] Create a favorite recipe view that filters only recipes the user has liked or rated
 - Use `get_queryset` to filter the queryset with only user favorited recipes
- [x] Create template to view a users liked recipes

#
