### ISSUE TITLE
USER STORY: Cloudinary Setup

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#4]
As a **developer**, I can **create a Cloudinary account** so that **I can store my media files**

### Related User Stories:
#

### Tasks:
- [ ] Visit the Cloudinary website - https://cloudinary.com/
- [ ] Click on the 'sign up for free' button
- [ ] Provide name, email address and choose a password
- [ ] Choose Programmable Media for image and video API
   - [ ] Edit the assigned cloud name to something more appropriate
- [ ] Click Create Account
- [ ] Verify your email and you will be brought to the dashboard
