### ISSUE TITLE
USER STORY: Create a database

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#40]
### User Story:
As a **developer**, I should **set up the necessary database items** so that **the database is viewable through Heroku**

#
### Relevant Information:
- The database provided by Django is only accessible within Gitpod and is not suitable for a production environment. Your deployed project on Heroku will not be able to access it. So, you need to create a new database that can be accessed by Heroku. 
# 

### Related User Stories:
- #1 - **Create Heroku app**

#
### Tasks:
- [ ] Log in to [ElephantSQL.com](https://www.elephantsql.com/) to access your dashboard
- [ ] Click 'Create New Instance'
- [ ] Set up your plan
     - Give your plan a Name (this is commonly the name of the project)
     - Select the Tiny Turtle (Free) plan
     - You can leave the Tags field blank
- [ ] Select 'Select Region'
- [ ] Select a data center near you and click 'Review'
- [ ] Create an instance
- [ ] Return to the ElephantSQL dashboard and click on the database instance name for this project
- [ ] In the URL section, click the copy icon to copy the database URL

#
