### ISSUE TITLE
USER STORY: Like a recipe

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#42]
### User Story:
As a **logged-in User**, I can **like or star a recipe** so that **I can bookmark it for later**
#

### Ideas:
- Use fontawesome to display either a star, thumbs up, or heart icon
#
### Acceptance Criteria:
- Only a logged-in user can like a recipe and save it to their personal liked recipes
- The like button should be displayed at the top of the recipe near to the last updated date
- The user should know if they have liked a recipe by the change in colour or state of the logo
- The recipe should be saved into a user's liked recipes page after being clicked and taken out when it's been unliked
#

### Related User Stories:
#12 - **View most liked recipes**
#39 - **View my liked recipes**
#

### Tasks:
- [x] Create A like option within the recipe model 
- [x] Create a button for a user to select on the recipe detail page 
- [ ] Link the saved recipe to a users saved personal list
     - #39 - View my liked recipes
#
