### ISSUE TITLE
USER STORY: Deploy using GitHub

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#5]
### User Story:
As a **developer**, I can **connect my GitHub account for the final deployment stages** so that **I can allow deployment to production**
#

### Related User Stories:
#

### Tasks:
- [x] Connect your GitHub account from the deployment method of settings in your Heroku app
- [x] Select the correct repository and click connect
- [x] Enable Automatic deploys from the main branch
- [x] Click deploy branch and watch Heroku build your app from the buildpack window

#
