### ISSUE TITLE
USER STORY: Django Setup

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#6]
### User Story:
As a **developer**, I can **set up Django and supporting libraries** so that **I can start developing the site**
#

### Relevant Information:
- Django 3.2 is the LTS (Long Term Support) version of Django and is therefore preferable to use over the newest Django 4

#
### Related User Stories:
#7 - **Django Secure my secret keys**

#8 - **Install Django-allauth**

#9 - **Installing Django-crispy-forms**

#28 - **Admin CRUD features**

#
### Tasks:
- [x] Install Django - `pip3 install 'django<4' gunicorn`
- [x] Install `pip3 install dj_database_url==0.5.0 psycopg2`
- [x] Install `pip3 install dj3-cloudinary-storage`
- [x] Create a requirements.txt file
   - `pip3 freeze --local > requirements.txt`
- [x] Create the Django project - `django-admin startproject <projectname> .`
- [x] Create the first app – called 'recipes' and add it to `INSTALLED_APPS` in `settings.py`
   - `python3 manage.py startapp recipes`
- [x] Migrate changes to the database
   - `python3 manage.py migrate`

- [x] #7 Secure my secret keys
#
