### ISSUE TITLE
USER STORY: Django Secure my secret keys

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#7]
### User Story:
As a **developer**, I want to **set up my environment to secure my private keys** so that **I do not expose them in an insecure way**
#

### Related User Stories:
#
### Tasks:
- [x] Create an `env.py` file to store the environment variables/API keys and database secret keys
- [x] Amend the Django code to access the new locations for the secret keys
- [x] Add the `env.py` file to the `.gitignore` file so that it does not get pushed to GitHub

#
