### ISSUE TITLE
USER STORY: Install Django-allauth

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#8]
### User Story:
As a **developer**, I should **install the necessary Django components** so that **I can address authentication, registration, and account management for users**
#

### Related User Stories:
#6 Django Setup - As a **developer**, I can **set up Django and supporting libraries** so that **I can start developing the site**
#

### Tasks:
- [x] Install `pip3 install django-allauth` to create the account management system for users
- [x] Update requirements.txt - `pip3 freeze --local > requirements.txt`
- [x] Add the URL path in urls.py
- [x] Update `INSTALLED_APPS` in settings.py
    - [x] Add `django.contrib.sites`
    - [x] Add `allauth`
    - [x] Add `allauth.account`
    - [x] Add `allauth.socialaccount`
- [x] Add `SITE_ID = 1` below `INSTALLED_APPS`
- [x] Add `LOGIN_REDIRECT_URL = '/'` below `SITE_ID`
     - [x]  `LOGOUT_REDIRECT_URL = '/'`   
- [x] Add `ACCOUNT_EMAIL_VERIFICATION = 'none'`
- [ ] Run Migrations - `python3 manage.py migrate` 

- [ ] Install templates folder `cp -r ../.pip-modules/lib/python3.8/site-packages/allauth/templates/* ./templates` in the command line
- [ ] Edit templates

#
