### ISSUE TITLE
USER STORY: Installing Django-crispy-forms

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/PP4-Kitchen_Tales#9]
### User Story:
As a **developer**, I should **install the necessary Django components** so that **I can display a comments section**
#

### Related User Stories:
#6 Django Setup - As a **developer**, I can **set up Django and supporting libraries** so that **I can start developing the site**
#
### Tasks:
- [x] Install `pip3 install django-crispy-forms`
- [x] Update requirements.txt - `pip3 freeze --local > requirements.txt`
- [x] Update `INSTALLED_APPS` in settings.py
    - Add `crispy_forms`
- [x] Add `CRISPY_TEMPLATE_PACK = 'bootstrap4'` below `INSTALLED_APPS`
- [x] Add a new folder forms.py
    - Import relevant data `from .models import Comment` `from django import form`
- [x] In views.py file import `from .forms import CommentForm`
- [x] Render as a view 
- [x] Add the form to the HTML file
    - Add security to all forms `{% csrf_token %}` (cross site request forgery)
- [x] Add post data to views.py

#
